language: php

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.composer/cache/files
    - ${TRAVIS_BUILD_DIR}/travis/extension-cache

php:
    - 7.1

env:
    - ILLUMINATE_VERSION=5.1.* PHPUNIT_VERSION=~4.0
    - ILLUMINATE_VERSION=5.2.* PHPUNIT_VERSION=~4.0
    - ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0
    - ILLUMINATE_VERSION=5.4.* PHPUNIT_VERSION=~5.7
    - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0
    - ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0 COVERAGE=true
    - ILLUMINATE_VERSION=5.6.* PHPUNIT_VERSION=~7.0

matrix:
    # For each PHP version we exclude the coverage env, except for PHP 7.1
    exclude:
        # Test only Laravel 5.4 and 5.5 on PHP 7.1
        - php: 7.1
          env: ILLUMINATE_VERSION=5.1.* PHPUNIT_VERSION=~4.0
        - php: 7.1
          env: ILLUMINATE_VERSION=5.2.* PHPUNIT_VERSION=~4.0
        - php: 7.1
          env: ILLUMINATE_VERSION=5.3.* PHPUNIT_VERSION=~5.0
        - php: 7.1
          env: ILLUMINATE_VERSION=5.5.* PHPUNIT_VERSION=~6.0

before_install:
    - cp ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
    - phpenv config-rm xdebug.ini
    - composer global require hirak/prestissimo --update-no-dev
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update --prefer-dist
    - composer require "orchestra/testbench:${ILLUMINATE_VERSION/5\./3\.}" --no-update --prefer-dist
    - composer require "phpunit/phpunit:${PHPUNIT_VERSION}" --no-update --prefer-dist

install: travis_retry composer install --no-interaction --prefer-dist

before_script: phpenv config-add ~/xdebug.ini

script: vendor/bin/phpunit

after_success: sh -c "if [ ! -z ${COVERAGE+x} ]; then php vendor/bin/coveralls; fi"

notifications:
    email: false
